---
title: "wrapup_assignment"
format: pdf
editor: visual
---

## Modelling Framework and Analysis Plan

The goal of this assignment is to use what you've been learning in the course to develop a clear, well-structure plan for using a model in an environmental problem solving context. You won't actually implement and run the model but you will create a plan that would ensure that your modeling endeavor is credible and effective.

## Steps

### Modeling Question

In 1 paragraph describe the overall goal of your environmental problem solving effort and how modeling will help you to achieve that goal. Include a specific modeling question that you would want to answer as part of the effort

### Conceptual Model

Given the question that you are asking with the model - describe you conceptual model - what are the key components of the system that you need to represent to answer your question. Draw a diagram to illustrate your conceptual model and include a brief description of the components and relationships in your model.

### Model Design

Create a list of inputs, parameter and outputs for your model - include units (or spatial-temporal scale) e.g a 30m digital elevation model, daily time series of precipitation for 3 locations in the watershed

Identify what type of model you will use using the classification from class

If you know of an existing off the shelf model that you would use - provide a citation.

Describe what observations might be used to evaluate the model performance - what metric might you use in that evaluation? E.g RMSE between observed and modeled streamflow at daily time steps over a 5 year period

### Analysis Plan

Describe how you would use the model to answer your modeling question. What scenarios would you run in order to answer your question? What are 2-3 key metrics that you would use to summarize model outputs to answer your question?

Which parameters might you focus on in an uncertainty analysis? Provide details on how you would do this (e.g how would you sample the parameters, how would you estimate parameter ranges, how might you visualize and/or quantify the results of the uncertainty analysis)


### Assumptions

List 2-3 assumptions that you would want to include in a summary of model findings

## Grading

1. Model goal is clearly articulated (5pts) and the modeling question (5pts) is specific and related to the goal (total 10 points)
2. Conceptual model is clearly described (5pts) and the diagram (5pts) effectively illustrates the key components and relationships (total 10 points)
3. Model design includes a list of inputs/parameters (10pts), and outputs (10pts) with appropriate units (20 points total) 
4. Model type is correctly identified and an appropriate existing model is cited if applicable (10 points)
5. Evaluation plan includes meaningful observations (10pts) and appropriate metrics (10pts) for assessing model performance (total 20 points)
6. Analysis plan includes clear scenarios (10pts), key metrics (10pts), and  plans
for uncertainty/sensitivity analyses (10pts) (total 30 points)
7. Assumptions are relevant to the modeling effort, at least 2 assumptions listed (10 points)
